// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpogscjqucvmihicufqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwb2dzY2pxdWN2bWloaWN1ZnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTczODcsImV4cCI6MjA2NTYzMzM4N30.MmvuU99myU4cnS8pqbS8Oiyid_RBEptQy3A4jKNgdWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);